[package]
name = "rust-pong"
version = "0.1.0"
authors = ["Donovan Preston <donovanpreston@gmail.com>"]

[[bin]]
name = "rust-pong"

[dependencies]
piston = "0.35.0"
piston2d-graphics = "0.24.0"
pistoncore-glutin_window = "0.43.0"
piston2d-opengl_graphics = "0.50.0"
piston-music = "0.24.0"
